select ID,NAME,COUNTRIES,FYEAR from products WHERE ID NOT IN (102);

ALTER TABLE PRODUCTS ADD COLUMN COUNTRIES CHARACTER VARYING(500);

ALTER TABLE PRODUCTS ADD COLUMN FYEAR INTEGER DEFAULT 2000;


UPDATE PRODUCTS SET COUNTRIES=COUNTRIES||',iTALY'  WHERE ID NOT IN (108,109,110)



SELECT NAME||'-'||COUNTRIES||'-'||FYEAR AS PRODUCT_NAME FROM PRODUCTS;

#SPLIT_PART(INPUT,DELIMITER,POSITION)

SELECT * FROM (
SELECT ID,NAME,SPLIT_PART(COUNTRIES,',',7) AS MAPPED_COUNTRY FROM PRODUCTS ) AS TB
WHERE MAPPED_COUNTRY='';


SELECT NAME,COUNTRIES FROM PRODUCTS WHERE ID =103;